#![allow(unused)]

pub mod utils;
pub mod sys;
pub mod api;



library_exports!{
    image_open => crate::api::image::open,
    image_open_with_format => crate::api::image::open_with_format,
    image_create => crate::api::image::create,
    image_dimensions => crate::api::image::dimensions,
    image_crop => crate::api::image::crop,
    image_color => crate::api::image::color,
    image_grayscale => crate::api::image::grayscale,
    image_invert => crate::api::image::invert,
    image_resize => crate::api::image::resize,
    image_thumbnail => crate::api::image::thumbnail,
    image_blur => crate::api::image::blur,
    image_unsharpen => crate::api::image::unsharpen,
    image_filter3x3 => crate::api::image::filter3x3,
    image_adjust_contrast => crate::api::image::adjust_contrast,
    image_brighten => crate::api::image::brighten,
    image_huerotate => crate::api::image::huerotate,
    image_flipv => crate::api::image::flipv,
    image_fliph => crate::api::image::fliph,
    image_rotate90 => crate::api::image::rotate90,
    image_rotate180 => crate::api::image::rotate180,
    image_rotate270 => crate::api::image::rotate270,
    image_save => crate::api::image::save,
    image_save_with_format => crate::api::image::save_with_format,
    image_map_rgba => crate::api::image::map_rgba,
    image_reduce_rgba => crate::api::image::reduce_rgba,
    image_map_luma => crate::api::image::map_rgba,
    image_reduce_luma => crate::api::image::reduce_rgba,
    grayimage_u32_map => crate::api::image::map_grayimage_u32,
    grayimage_u32_reduce => crate::api::image::reduce_grayimage_u32,
    grayimage_u32_to_image => crate::api::image::grayimage_u32_to_image,
    image_adaptive_threshold => crate::api::image::adaptive_threshold,
    image_equalize_histogram => crate::api::image::equalize_histogram,
    image_match_histogram => crate::api::image::match_histogram,
    image_otsu_level => crate::api::image::otsu_level,
    image_stretch_contrast => crate::api::image::stretch_contrast,
    image_threshold => crate::api::image::threshold,
    image_distance_transform => crate::api::image::distance_transform,
    image_canny => crate::api::image::canny,
    image_box_filter => crate::api::image::box_filter,
    image_gaussian_blur_f32 => crate::api::image::gaussian_blur_f32,
    image_horizontal_filter => crate::api::image::horizontal_filter,
    image_median_filter => crate::api::image::median_filter,
    image_separable_filter => crate::api::image::separable_filter,
    image_separable_filter_equal => crate::api::image::separable_filter_equal,
    image_sharpen3x3 => crate::api::image::sharpen3x3,
    image_sharpen_gaussian => crate::api::image::sharpen_gaussian,
    image_vertical_filter => crate::api::image::vertical_filter,
    image_morph_close => crate::api::image::morph_close,
    image_morph_dilate => crate::api::image::morph_dilate,
    image_morph_erode => crate::api::image::morph_erode,
    image_morph_open => crate::api::image::morph_open,
    image_gaussian_noise => crate::api::image::gaussian_noise,
    image_salt_and_pepper_noise => crate::api::image::salt_and_pepper_noise,
    image_connected_components => crate::api::image::connected_components,
    image_shrink_width => crate::api::image::shrink_width,
}

